name: dotrun
base: core18

version: "1.1.8"

summary: A command-line tool for running Node.js and Python projects

description: |
  A command-line tool for running Node.js and Python projects
  from Canonical's webteam

grade: stable
confinement: strict

parts:
  node:
    plugin: dump
    source: https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.4.0-1nodesource1_amd64.deb

  yarn:
    plugin: dump
    source: https://github.com/yarnpkg/yarn/releases/download/v1.22.0/yarn_1.22.0_all.deb

  semwraplib:
    plugin: dump
    source: src
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      gcc -g -O0 -Wall -Wstrict-prototypes -fPIC -shared lib.c -o $SNAPCRAFT_PART_INSTALL/lib/semwraplib.so -ldl
    build-packages:
      - build-essential

  dotrun-module:
    plugin: python
    source: src
    stage-packages:
      - curl
      - gettext
      - git
      - build-essential
      - python3-dev
      - libjpeg-progs
      - libmagickwand-dev
      - libpng-dev
      - libpq-dev
      - libsodium-dev
      - gpg
      - optipng
      - zlib1g-dev

plugs:
  dot-npmrc:
    interface: personal-files
    read:
      - $HOME/.npmrc
  dot-yarnrc:
    interface: personal-files
    read:
      - $HOME/.yarnrc

apps:
  dotrun:
    command: dotrun
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LC_CTYPE: C.UTF-8
      LD_PRELOAD: $SNAP/lib/semwraplib.so
    plugs:
      - home
      - network
      - network-bind
      - process-control
      - dot-npmrc
      - dot-yarnrc
