name: dotrun
base: core18
version: '1.0.0-rc5'
summary: A command-line tool for running projects
description: |
  A command-line tool for running projects

grade: stable
confinement: strict

parts:
  node:
    plugin: dump
    source: https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.4.0-1nodesource1_amd64.deb

  yarn:
    plugin: dump
    source: https://github.com/yarnpkg/yarn/releases/download/v1.22.0/yarn_1.22.0_all.deb

  dotrun-module:
    plugin: python
    source: .

apps:
  dotrun:
    command: dotrun
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      LC_CTYPE: C.UTF-8
    plugs:
      - home
      - network
      - network-bind
      - process-control
