name: dotrun
base: core18
version: '0.2.4'
summary: A command-line tool for running projects
description: |
  A command-line tool for running projects

grade: stable
confinement: devmode

parts:
  system-packages:
    plugin: nil
    stage-packages:
      - python3-pip

  node:
    plugin: dump
    source: https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.4.0-1nodesource1_amd64.deb

  yarn:
    plugin: dump
    source: https://github.com/yarnpkg/yarn/releases/download/v1.16.0/yarn_1.16.0_all.deb

  dotrun-module:
    plugin: python
    source: .

apps:
  dotrun:
    command: dotrun
    plugs:
      - home
      - network
      - network-bind
      - process-control
