name: PR
on: [pull_request]

jobs:
  test-snap:
    runs-on: ubuntu-latest
    name: Test snap
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo chown root:root /

      - name: Install dotrun snap
        run: |
          /snap/bin/snapcraft --destructive-mode
          sudo snap install --dangerous dotrun_*.snap

      - name: Run tests
        run: |
          pip3 install pexpect
          export PATH=/snap/bin:$PATH
          python3 -m unittest discover --verbose --start-directory tests

  lint-python:
    runs-on: ubuntu-latest
    name: Lint python

    steps:
      - uses: actions/checkout@v1

      - name: Install system dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install flake8 black
      - name: Lint Python
        run: flake8 . && black --line-length 79 --check .
