name: Yarn test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo chown root:root /
      - name: Install dotrun snap
        run: |
          snapcraft --destructive-mode
          sudo snap install --dangerous *.snap
      - name: Get help
        run: dotrun --help
